### ISSUE TITLE
Need better documentation on specifying a collection name as part of facet command

### ISSUE THREAD

**Issue by epugh** [lucidworks/zeppelin-solr#11]
I just discovered that I can pass in a collection parameter, instead of having to use `use mycollection`.   This isn't documented anywhere, except as a cryptic error message.

If you run `facet` your get baack the message `Specify the query params to facet with. Example: search q=text&facet=true&facet.field=genre`, it could also put in the `collection=yourcollection` parameter in that messaage!

Or do we need to updaate/enahnce the README?

**Comment by kiranchitturi** [comment]
facet might work fine but I don't think other commands like stream or sql will work. We can document for facet param. I will update the README for now 👍 

I just committed minor fixes and releasing 0.1.1 that fixes logging

**Comment by kiranchitturi** [comment]
Released 0.1.1 and updated the README
