### ISSUE TITLE
Feedback from using 0.1.4

### ISSUE THREAD

**Issue by epugh** [lucidworks/zeppelin-solr#19]
I just updated `to 1.0.4` from `beta3` and wanted to provide some feedback.   Wasn't sure if you'd rather this on the Solr Dev mailing list instead?

1. The `list` command disappeared, however we could support that right?   Hit the cores API or the colections API?   I like the "list" just to sanity check I have a working connection to the environment htat I think I have!

1.1 Related, when I run `use`, we no longer get the details from Luke aobut the structure of the core..   That was a nice tool for exploring...   I wonder if a `describe` command would be useful?

2. We need to better specify that `solr.baseUrl` is the new parameter.   I was upgrading, so my interpreter faffed around a bbit.  But in the docs saying `solr.baseUrl=http://localhost:8983/solr` would be helpful.   So glad to be not tied to ZK!

**Comment by joel-bernstein** [comment]
Yeah, this is a stepping stone release to break the tie to Zk. Over time I'd like to add more data exploration features as Streaming Expressions. For example we can implement list() to list collections and fields(collections) to list fields. This way these function will be available outside of zeppelin as well and can be combined with other expressions. Thanks for the feedback, and I'm glad the break from Zk helps your use cases.

**Comment by epugh** [comment]
@joel-bernstein feel free to close this ticket!
