### ISSUE TITLE
SQL Queries don't display column names lined up with column content..

### ISSUE THREAD

**Issue by epugh** [lucidworks/zeppelin-solr#25]
I just bumped up to the 0.1.5, and a query like below runs, but the column names don't match to the column fields!  
```
%solr
select * from dev_raw_data limit 10
```

**Comment by epugh** [comment]
the `search` syntax still works properly!

**Comment by joel-bernstein** [comment]
I'm pretty sure select * is not supported in Solr SQL. Have you configured a different SQL backend?

**Comment by epugh** [comment]
Okay, I tried `select metadata,status_str from dev_raw_data limit 10` and it worked as expected.  I swore that select * worked, as that is my default to explore a collection in 0.1.4.   Looking back at https://lucene.apache.org/solr/guide/7_7/parallel-sql-interface.html#solr-collections-and-db-tables (ready to prove you wrong), it does say * doesn't work...   I'd love to know why!!

Maybe since this is so common syntax, we should add it to https://lucene.apache.org/solr/guide/7_7/parallel-sql-interface.html#solr-sql-syntax?

**Comment by epugh** [comment]
Added https://issues.apache.org/jira/browse/SOLR-13461 and https://github.com/apache/lucene-solr/pull/671

**Comment by epugh** [comment]
This has been dealt with!
