### ISSUE TITLE
Kerbersos authentication

### ISSUE THREAD

**Issue by jalongar** [lucidworks/zeppelin-solr#4]
Hi,
In case of a kerberized cluster, How I can include the information about keytab and principal in order to connect ?

Regards

**Comment by kiranchitturi** [comment]
I think kerberos can be enabled by setting `-Djava.security.auth.login.config=/path/to/jaas.conf` in both driver and executor javaOptions

**Comment by kiranchitturi** [comment]
kerberos can be enabled by setting `-Djava.security.auth.login.config=/path/to/jaas.conf` in both driver and executor javaOptions

**Comment by kiranchitturi** [comment]
Kerberos can be enabled by passing jaas conf file via jvm system param `java.security.auth.login.config`
