### ISSUE TITLE
basic auth

### ISSUE THREAD

**Issue by aroopganguly** [lucidworks/zeppelin-solr#5]
Hello!

In case I have basic auth setup on my solr cluster/instance, how do I provide the same?

Thanks
Aroop

**Comment by kiranchitturi** [comment]
@aroopganguly Currently, zeppelin-solr does not support basic auth.

**Comment by aroopganguly** [comment]
@kiranchitturi does it support any other kind of auth like kerberos?

**Comment by kiranchitturi** [comment]
yes, it does support kerberos. Kerberos can be enabled by setting jvm param `-Djava.security.auth.login.config=/path/to/jaas.conf` to zeppelin JVM

**Comment by aroopganguly** [comment]
thanks !
