### ISSUE TITLE
total document counts do not match 

### ISSUE THREAD

**Issue by aroopganguly** [lucidworks/zeppelin-solr#7]
Hi Team

I am observing a discrepancy between the actual number of documents in a collection and the number shown in the zeppelin-notebook when performing "use <collection-name>" command.

The one on the UI after the use command is significantly lower than the actual.
Also when I run a facet or streaming expression query the doc counts are significantly higher than the total docs shown in the section created using the "use" command.

**Comment by kiranchitturi** [comment]
yeah, it's a bug. The luke query was not distributed. I am fixing it in the next version

**Comment by kiranchitturi** [comment]
fixed in #10
